language: python
python:
  - 3.6

# Update pip to the latest version
before_install:
  - python --version
  - pip install -U pip

install:
  - pip install -r requirements.txt

#script:
#  - python -m unittest tests/power_digit_addition_tests.py

deploy:
  provider: pypi
  username: "vijayshinde"
  password: "pypi-AgEIcHlwaS5vcmcCJDc3NjNjOThmLWUwNDctNGM2MC05OTVmLTk0NThkYjUyOTc4ZQACRXsicGVybWlzc2lvbnMiOiB7InByb2plY3RzIjogWyJwb3dlci1kaWdpdC1hZGRpdGlvbiJdfSwgInZlcnNpb24iOiAxfQAABiDJATUFqrCgb7lzXPYKdOwb3ucGODQkkgmC333Oi5BxkA"
  on:
    branch: main
